-- MySQL Script generated by MySQL Workbench
-- Fri Dec 22 17:43:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_db` DEFAULT CHARACTER SET utf8 ;
USE `library_db` ;

-- -----------------------------------------------------
-- Table `library_db`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`books` (
  `idbooks` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `cover` VARCHAR(45) NULL,
  `pages_no` INT NULL,
  `category` VARCHAR(45) NULL,
  `isbn` VARCHAR(45) NULL,
  `publish_year` INT NULL,
  `edition` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `avilable` TINYINT NULL,
  `borrowers` VARCHAR(45) NULL,
  `publisher` VARCHAR(45) NULL,
  PRIMARY KEY (`idbooks`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
